<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Netchex-015" name="Test Automation Framework" tests="4" failures="2" timestamp="31 May 2019 10:32:33 GMT" time="32.496" errors="0">
  <testcase name="LoginToApplication1" time="1.063" classname="MDM.Automation_Test.LoginTest">
    <failure type="junit.framework.AssertionFailedError" message="Login Failed 1">
      <![CDATA[junit.framework.AssertionFailedError: Login Failed 1
	at junit.framework.Assert.fail(Assert.java:50)
	at junit.framework.Assert.assertTrue(Assert.java:20)
	at MDM.Automation_Test.LoginTest.LoginToApplication1(LoginTest.java:26)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- LoginToApplication1 -->
  <testcase name="LoginToApplication2" time="2.39" classname="MDM.Automation_Test.LoginTest"/>
  <testcase name="LoginToApplication3" time="1.104" classname="MDM.Automation_Test.SampleTest">
    <failure type="junit.framework.AssertionFailedError" message="Login Failed 1">
      <![CDATA[junit.framework.AssertionFailedError: Login Failed 1
	at junit.framework.Assert.fail(Assert.java:50)
	at junit.framework.Assert.assertTrue(Assert.java:20)
	at MDM.Automation_Test.SampleTest.LoginToApplication3(SampleTest.java:26)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- LoginToApplication3 -->
  <testcase name="LoginToApplication4" time="2.447" classname="MDM.Automation_Test.SampleTest"/>
</testsuite> <!-- Test Automation Framework -->
